ls | while read d; do rename 's/(.*)/\L$1/' $d; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*/*/*/*/*/*; done
ls | while read d; do rename 's/(.*)/\L$1/' $d/*/*/*/*/*/*/*/*/*/*/*/*; done
