#!/bin/bash

# Handy when one has two different dropbox accounts :)

if [ -n $(pgrep -f "dropbox-dist") ]; then
    HOME=$HOME/dropbox-insekten
    dropbox start &> /dev/null
else
    dropbox stop
fi
