#!/bin/bash

# Rename things to be nice for linux, rsync and anything else useful
if [ "$PWD" == ~ ]; then 
    echo "Don't do this in your home directory..."; exit;
fi

find . -type d -name '* *' | while read file; do
    target=`echo "$file" | sed -r -e 's/\ {1,}/-/g' -e 's/-{1,}/-/g' -e 's/-\_-/_/g' -e 's/\:/\_/g'` ;
    echo "Renaming '$file' to '$target'";
    mv "$file" "$target";
done;	

find . -name '* *' | while read file;
do
    target=`echo "$file" | sed -r -e 's/\ {1,}/-/g' -e 's/-{1,}/-/g' -e 's/-\_-/_/g'`;
    echo "Renaming '$file' to '$target'";
    mv "$file" "$target";
done;

find . -name '*:*' | while read file;
do
    target=`echo "$file" | sed -r -e 's/:/_/g'`;
    echo "Renaming '$file' to '$target'";
    mv "$file" "$target";
done;
