#!/bin/bash

# Rename things to be nice for linux, rsync and anything else useful
if [ "$PWD" == ~ ]; then 
    echo "Don't do this in your home directory..."; exit;
fi

if [ "$PWD" == / ]; then 
    echo "Don't do this in your root directory..."; exit;
fi

find . -type d |
    sed -r '/\.svn/d;/\.git/d;/README/d;/^Make.*/d;/LICENSE/d;/.*[A-Z :].*/!d' |
    while read file;
    do
        target=$(echo "$file" | sed -r -e 's/\ +/-/g;s/-+/-/g;s/-?\_-/_/g;s/\:/\_/g') ;
        # echo "Renaming '$file' to '$target'";
        mv "$file" "$target";
        target2=$(echo "$target" | sed -r -e 's/\ +/-/g;s/-+/-/g;s/-\_-?/_/g');
        # echo "Renaming '$target' to '$target2'";
        mv "$target" "$target2";
        target=$(echo "$target2" | sed -r -e 's/:/_/g');
        # echo "Renaming '$target2' to '$target'";
        mv "$target2" "$target";
        target2=$(echo "$target" | sed -r -e 's/[A-Z]/\L&/g');
        echo "Renaming '$file' to '$target2'";
        mv "$target" "$target2";
    done

echo now rename files

find . -type f |
    sed -r '/\.pio/d;/\.svn/d;/\.git/d;/README/d;/LICENSE/d;/.*[A-Z :].*/!d' |
    rename -v 's/[A-Z]/\L$&/g;s/ +/-/g;s/:/_/;s/-_-/_/g;s/-+/-/g;s/_-_/-/g'
